name: groupie
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.2.10
  firebase_auth_web: ^5.3.1
  firebase_core: ^2.9.0
  firebase_core_web: ^2.3.0
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  font_awesome_flutter: ^10.5.0
  google_sign_in: ^6.1.4
  google_sign_in_web: ^0.12.0+2
  google_sign_in_web_redirect: ^0.0.1
  shared_preferences: ^2.0.18

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: arial
      fonts:
        - asset: assets/fonts/ArialTh.ttf
          weight: 700
